labelPRBasedOnFilePath:
  documentation:
    - docs/*
    - docs/**/*

  constructs:
    - src/constructs/*
    - src/constructs/**/*

  commons:
    - src/common/*
    - src/common/**/*

  stacks:
    - src/stacks/*
    - src/stacks/**/*  

  tests:
    - test/*
    - test/**/*

firstPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

verifyTitles:
  titleRegexp: ^(feat|fix|docs|refactor|test|chore)\((stacks|commons|constructs|layers|ci|docs|structure)\):.*
  alwaysUsePrTitle: true
  validateEitherPrOrSingleCommitTitle: true
  statusTitle: "Title Validator"
  successMessage: "Validation successful!"
  failureMessage: "Wrong ${type} title: ${title}"
