# conventional commit types: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
types:
  - feat
  - fix
  - docs
  - refactor
  - test
  - chore

scopes:
  - stacks
  - commons
  - constructs
  - layers
  - ci
  - docs
  - structure
