
name: Publish docs

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      py_version:
        description: PY version
        default:  3.9
  
env:
  PYTHON_VERSION: ${{ github.event.inputs.py_version }}

jobs:
  release-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Build docs
        run: |
          cd docs
          yarn install
          yarn build

      - name: Publish docs on github pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
